src/force-app/main/default/objects/Case_Jira_AppFire_Setting__mdt/Case_Jira_AppFire_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Used for Custom Settings that affect APEX for the MCG Case Escalation work that uses the AppFire Jira Integration. Case 00391891 TCE 3/11/2025</description>
    <label>Case Jira AppFire Setting</label>
    <pluralLabel>Case Jira AppFire Settings</pluralLabel>
</CustomObject>

src/force-app/main/default/objects/Case_Jira_AppFire_Setting__mdt/fields/Allow_Sandbox_to_Send__c.field-meta.xml
<CustomField>
    <fullName>Allow_Sandbox_to_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This should always be set to False unless you are testing. This will cause the sandbox to send to the configured installed package JCFS.API. Default is disabled. Created 03/21/2025 TCE</description>
    <inlineHelpText>Check this to allow the Sandbox to send API messages to the installed JCFS.API package. The JCFS.API package should be connected to a Jira Sandbox. The default for this setting is false. This setting should be disabled when not in use. This setting should be disabled in Production.</inlineHelpText>
    <label>Allow Sandbox to Send</label>
    <type>Checkbox</type>
</CustomField>

src/force-app/main/default/objects/Case_Jira_AppFire_Setting__mdt/fields/Issue_ID__c.field-meta.xml
<CustomField>
    <fullName>Issue_ID__c</fullName>
    <description>Issue ID is the Issue Type. MCG has 20 or 30 when this was built.</description>
    <inlineHelpText>The Issue Id comes from the connected Jira Environment. The Jira Admin will give you this. This setting should be confirmed and updated when using in Sandbox. This setting is confgiured for Production after a Sandbox Refresh.</inlineHelpText>
    <label>Issue ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Case_Jira_AppFire_Setting__mdt/fields/JCFS_API_Apex_Enabled__c.field-meta.xml
<CustomField>
    <fullName>JCFS_API_Apex_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls if the JCFS API is called via Apex. Created 3/21/2025 TCE</description>
    <inlineHelpText>Check this to use the JCFS.API Apex Triggers. If disabled, all of the Apex Code is skipped, simimar to if there were not config settings. If you are having trouble with API or Apex related to this is broken, try to disable this setting.</inlineHelpText>
    <label>JCFS API Apex Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/force-app/main/default/objects/Case_Jira_AppFire_Setting__mdt/fields/JCFS_API_Use_Advanced_API__c.field-meta.xml
<CustomField>
    <fullName>JCFS_API_Use_Advanced_API__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This setting is used by Apex to determine if we send a case list the JCFS API (recommended). Created 03/22/2025 TCE</description>
    <inlineHelpText>Check this to use the Advanced API. This is the default setting. The Basic API does not send a case list to the JCFS.API tooling. If you are having trouble with API calls, try to disable this setting.</inlineHelpText>
    <label>JCFS API Use Advanced API</label>
    <type>Checkbox</type>
</CustomField>

src/force-app/main/default/objects/Case_Jira_AppFire_Setting__mdt/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <description>Used for Custom Settings that affect APEX for the MCG Case Escalation work that uses the AppFire Jira Integration. Case 00391891 TCE 3/11/2025</description>
    <inlineHelpText>The Project Id comes from the connected Jira Environment. The Jira Admin will give you this. This setting should be confirmed and updated when using in Sandbox. This setting is confgiured for Production after a Sandbox Refresh.</inlineHelpText>
    <label>Project ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

classes/Case_Escalation_AppFire_API.cls
/*
*********************************************************
Apex Class Name    : Case_Escalation_AppFire_API
Created Date       : March 11, 2025
@description       : Used to send the API call to the AppFire API for Case Escalations
@author            : Troy Center
Modification Log:
Ver   Date         Author                   Case            Modification    
1.0   03/11/2025   Troy Center              00000000        Initial Version, based on documentation from AppFire. 
                                                            AppFire Documentation: https://appfire.atlassian.net/wiki/spaces/CSFJIRA/pages/1873446010/Configure+Automatic+Pull+from+Salesforce
*********************************************************
*/
public class Case_Escalation_AppFire_API {
    public Case_Escalation_AppFire_API(List<Case> lstCasesIn, Map<Id,Case> mapOldCasesIn) {
        
        //Get Case Esclation AppFire Custom Metadata Settings
        String strAppFireSettingsString = 'Config'; 
        Case_Jira_AppFire_Setting__mdt AppFire_settings = Case_Jira_AppFire_Setting__mdt.getInstance(strAppFireSettingsString);                 

        //Check if AppFire Custom Settings are "Feature Enabled". 
        if(AppFire_settings != null && AppFire_settings.JCFS_API_Apex_Enabled__c == true){

            //Check if we are in a sandbox
            Boolean isASandbox = false;
            String domainName = System.DomainParser.parse(URL.getOrgDomainUrl()).getSandboxName();
            if(domainName != null && domainName != ''){
                isASandbox = true; 
            }

            //Get TSS Record Type, for create methood. 
            Id idTSSRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId();
                
            //Create List of Cases to Send Jira 
            List<Case> lstCasesToCreateInJira = new List<Case>();
            List<Case> lstCasesToUpdateInJira = new List<Case>();  
            List<Case> lstEmptyListOfCases = new List<Case>(); // Needed for "JSFS.API.createJiraIssue(String JiraProjectId, String JiraIssueTypeId, List<SObject> newObjects, List<SObject> oldObjects)"

            //Loop on the cases. 
            for(Case c : lstCasesIn){
                //If Open Case is updated that has a Jira ID. 
                if(c.isClosed == false && c.Jira_Id__c != null){
                    lstCasesToUpdateInJira.add(c); 
                }
                //Else If Escalate to SEAD, with no Jira ID, Create a Jira Item. 
                else if(c.Escalate_to_SEAD__c == true && 
                        c.Escalate_to_SEAD__c != mapOldCasesIn.get(c.Id).Escalate_to_SEAD__c && 
                        c.isClosed == false && 
                        c.Product__c != null && 
                        c.Jira_Id__c == null &&
                        c.Jira_AppFire_Create_Apex_Ran__c == null &&
                        c.RecordTypeId == idTSSRecordTypeId &&
                        (   
                            c.Priority == 'Level 1: Critical' || 
                            c.Priority == 'Level 2: Serious' || 
                            c.Priority == 'Level 3: Medium'
                        ) &&
                        (   
                            isASandbox == false || 
                            AppFire_settings.Allow_Sandbox_To_Send__c == true
                        )
                ){
                    lstCasesToCreateInJira.add(c); 
                }
            }

            // Get App Fire Settings to Send to
            String strJiraProjectId = AppFire_settings.Project_Id__c;
            String strJiraIssueId = AppFire_settings.Issue_Id__c;
            Boolean boolUseAdvancedAPI = AppFire_settings.JCFS_API_Use_Advanced_API__c; //Default is true.
            
            // Do Final Update on Case. Update the Case Date Field and Call the JCFS App API (Requires We Get the Cases again, Post Update, They are Read Only. )
            // using Jira_AppFire_Create_Apex_Ran__c to prevent duplicates by adding a date/time field to the case when we send it, Syncronously. 
            if(lstCasesToCreateInJira.size() > 0 && !System.isBatch() && !System.isFuture()){
                List<Case> lstCasestoCreateFinal = [SELECT Id, Jira_AppFire_Create_Apex_Ran__c, Jira_Id__c FROM Case WHERE Id IN: lstCasesToCreateInJira];    
                for(Case c : lstCasestoCreateFinal){    
                    c.Jira_AppFire_Create_Apex_Ran__c = System.now();
                    if(Test.isRunningTest()){       //If we ARE in a test run, MOCK the Jira ID. 
                        if(c.Jira_Id__c == null){
                            c.Jira_Id__c = 'TEST-999';
                        } 
                    }
                }
                update lstCasestoCreateFinal;   //Final update list we do not send to Jira, we send the trigger list to Jira.                    
            }
            // ***********************   Call JCFS CREATE *****************************
            // API Documentation: https://appfire.atlassian.net/wiki/spaces/CSFJIRA/pages/1873413628/Configuring+automatic+Jira+issue+creation+from+Salesforce
            // Pass all the objects you want to create a Jira issue from as newObjects. 
            // Note that all the objects in this list must be of the same runtime type. 
            // So we recommend using a concrete type, e.g. List<Case> or List<Account> for the variable, you pass as this parameter. 
            // ** The oldObjects parameter is not used at the moment so you can pass Trigger.old or an empty list for it.
            // ** MCG is using an empty list of cases, not Trigger.old (for triggers only)(is a List of Cases). 
            // ************************************************************************
            if(lstCasesToCreateInJira.size() > 0 && !System.isBatch() && !System.isFuture()){
                //Check the Custom Metadata Setting "JCFS API Use Advanced API"
                //Advanced API If Test Check and JCFS API call must be on the same line for Code Coverage. 
                if(boolUseAdvancedAPI == true && !Test.isRunningTest()){ JCFS.API.createJiraIssueWithDefaultPostAction(strJiraProjectId, strJiraIssueId, lstCasesToCreateInJira, lstEmptyListOfCases); } 
                if(boolUseAdvancedAPI == false && !Test.isRunningTest()){ JCFS.API.createJiraIssueWithDefaultPostAction(strJiraProjectId, strJiraIssueId); } 
            }                    
            // ***********************   Call JCFS Update *****************************
            // Our Apex API supports a selective pushing, so that you can exclude unwanted Salesforce objects from the push. For this purpose you can use the following API method:
            // Sample 1: JCFS.API.pushUpdatesToJira(List<SObject> newObjects, List<SObject> oldObjects)
            // Sample 2: JCFS.API.pushUpdatesToJira();
            // ** The oldObjects parameter is not used at the moment so you can pass Trigger.old or an empty list for it.
            // **   MCG is using an empty list of cases, not Trigger.old (for triggers only)(is a List of Cases). 
            // ************************************************************************
            if(lstCasesToUpdateInJira.size() > 0 && !System.isBatch() && !System.isFuture()){
                //Check the Custom Metadata Setting "JCFS API Use Advanced API"
                //Advanced API If Test Check and JCFS API call must be on the same line for Code Coverage. 
                if(boolUseAdvancedAPI == true && !Test.isRunningTest()){ JCFS.API.pushUpdatesToJira(lstCasesToUpdateInJira,lstEmptyListOfCases); }
                if(boolUseAdvancedAPI == false && !Test.isRunningTest()){ JCFS.API.pushUpdatesToJira(); }
            }
        }
    }
}